### ISSUE TITLE
Getting an Error message

### ISSUE THREAD

**Issue by DesignAgent** [mludowise/Sketch-HTML-Export#3]
When I go to Export to HTML this is what happens.
Please Advise.

![screen shot 2017-06-05 at 2 25 32 pm](https://cloud.githubusercontent.com/assets/17710322/26797587/5a416292-49fb-11e7-8980-d578890aae60.png)

**Comment by renatolaurino** [comment]
The same error here

**Comment by renatolaurino** [comment]
The same error here.

![captura de tela 2017-06-13 as 18 26 39](https://user-images.githubusercontent.com/7430666/27105420-e3ae30bc-5065-11e7-871b-3c08675c6579.png)

**Comment by mludowise** [comment]
Fixed
