### ISSUE TITLE
not working with Sketch 45.1

### ISSUE THREAD

**Issue by prasadajith** [mludowise/Sketch-HTML-Export#5]
when trying to export from Sketch 45.1 option window does not appear and export does not happen

**Comment by mludowise** [comment]
I'm unable to reproduce the problem. Can you please give me precise steps to reproduce including the following info:
- How many artboards are you trying to export?
- What are you selecting when attempting to export to HTML? Are you selecting the artboard or a layer inside the artboard?
- If you're comfortable attaching the Sketch file you're trying to export, that may be helpful as well.

Can you please also attach your logs. To export logs:
  1. Open **Console.app** located in the `/Applications/Utilities` folder.
  2. Expand **~/Library/Logs** in the left sidebar.
  3. Select **com.bohemiancoding.sketch** in the left sidebar.
  4. Select **Plugin Output.log** in the middle column.
  5. Reproduce the problem and copy the output from Console.app and attach it here.

![image](https://user-images.githubusercontent.com/1626168/27928750-437b0588-6245-11e7-8a5f-60eefed7c00f.png)

**Comment by prasadajith** [comment]
The problem occurs irrespective of the complexity of the sketch file 
It also happens irrespective of the number of artboards selected

I am attaching a simple sketch file i used to test it..

The console log shows as follows:

 Marker - Jul 7, 2017, 8:21:40 AM
SyntaxError: Unexpected identifier 'layer'.
Plugin “html”, line 106:
» 			let layer = selection.layers()[i];

 «Plugin Output»
 
[test.sketch.zip](https://github.com/mludowise/Sketch-HTML-Export/files/1129863/test.sketch.zip)

**Comment by mludowise** [comment]
@prasadajith What version of OS X are you on? (10.12.5 is the latest version)

Could you also tell me what version of Safari is installed on your computer? This will tell me what version of Javascript your system is using to interpret the plugin's code.

I think that your system might be running an older version of Javascript which doesn't recognize the `let` syntax. If that's the case, I'll change it so it's backwards compatible.

**Comment by prasadajith** [comment]
I am using OS X version 10.11.5 

Safari Version 9.1.1

Google Chrome Version 59.0.3071.115

Chrome is my default browser...

**Comment by mludowise** [comment]
@prasadajith Even though Chrome is your default browser, the version of Javascript that Sketch uses to execute plugins is in an OS X system library, JavaScriptCore, managed by Safari updates. I was using `let` syntax that is only supported in Safari 10 or higher.

I've reverted my change to be backwards compatible with Safari 9 so you shouldn't run into any more problems with HTML Export. You might want to update Safari so you don't run into any compatibility problems with other Sketch plugins. [Safari 10.1 is supported on El Capitan (10.11)](https://en.wikipedia.org/wiki/Safari_version_history#Version_compatibility), so you do not need to upgrade to OS X to Sierra.

**Comment by prasadajith** [comment]
That fixed the problem... it is now working with old version of safari...
thanks a lot for helping with this...
