### ISSUE TITLE
Export to HTML tag

### ISSUE THREAD

**Issue by HTKT** [mludowise/Sketch-HTML-Export#7]
Thanks for your good plugin. 

I tried to export the artboard to HTML but it seems to only have <div> tag for almost layers.
Can I export to HTML tag (e.g: button or img tag) by using this plugin ?

Thanks

**Comment by mludowise** [comment]
No, this plugin only supports exporting images or embedded SVG tag elements. It does not support any additional html tags such as buttons, text fields, etc.

The plugin is meant for quickly exporting a static html page and you would need to edit the html to add any other elements.
