### ISSUE TITLE
Has development of this plug-in been abandoned?

### ISSUE THREAD

**Issue by royrezentes** [mludowise/Sketch-HTML-Export#8]
I'm working with Sketch v49.3. This plug-in appears to work well exporting and positioning graphic assets, but not text boxes or background shapes. Any item (text, background shapes, etc) that are not marked for export are simply left off of the .html file. You can mark text and background shapes for export, but they end up being a graphic asset -- which is useless.

I'm a graphic designer trying to bridge the gap with web developers by exporting working .html and .css from my sketch files. If this plug-in has been abandoned, maybe you could point me to an alternative?

Thank you kindly,
Roy

**Comment by mludowise** [comment]
I still maintain the plugin if there are any bugs that arise as sketch is updated, but I have no plans to continue updating it beyond that. You, or anyone else, is welcome to contribute by making a pull request.

I’m not sure I understand what you’re asking for. Yes, you currently have to mark layers for export and they are exported as either PNG or SVG depending on which options you select. Are you trying to export actual HTML code instead? That’s a difficult problem to solve and I have no plans to expand this plugin to do that. The plugin is meant to export quick prototypes or mockups, but nothing beyond that.

You could look at click-thru-prototype to see if that’s closer to what you’re looking for:
https://github.com/markhorgan/click-thru-prototype



- Mel
________________________________

**Comment by royrezentes** [comment]
Thank you, Mel, for the quick reply and clarification. I also appreciate the recommendation of the click-thru-prototype. Cheers.
